### ISSUE TITLE
Arrange components inside src/ folder better

### ISSUE THREAD

**Issue by filipinacoder** [shagunmistry/ChallengeMe_ReactJS#2]
The components inside the /src folder is messy. Please group the related components together and place them in a folder. Ex: App.css , App.js should be inside /src/app folder

Even if a component only has one file, better store it in folder, folder name should be the component name.
So /src folder will contain subfolders that contain the components.

**Comment by shagunmistry** [comment]
I have reorganized the structure. Let me know if it could be structured better
